// current post July 15
// metaforms model for composite-component space.ts
export var Model1 = { scene: {
                        name: 'scene1',
                        camerasphere: null,
                        visible:{csphere:'off',key:'on',fill:'on',back:'on'}
                      },
                      shot:{},
                      branches:{},
                      actors: [
                        { id:'bb1',
                          form:{type:'billboard',
                                width: 20,
                                height: 20,
                                texture:{glad_png: './images/glad.png'}}, 
                          transform:{t:[-20,20,0]}, 
                          children:[]}, 
                        { id:'cone1',
                          form:{type:'cone',
                                opacity:0.7},
                          transform:{t:[0,-20,0]}, 
                          children:[]}, 
                        { id:'tetra1',
                          form:{type:'tetrahedron',
                                radius: 20,
                                opacity:0.4,
                                color:'white'},
                          transform:{t:[0,20,0]}, 
                          children:[]}, 
                        { id:'cube1',
                          form:{type:'cube',
                                width:10,
                                height:10,
                                depth:10,
                                texture:{p2_jpg: './images/p2.jpg'}}, 
                          transform:{t:[-15,-10,20]},
                          children:[]},
                        { id:'sphere1',
                          form:{type:'sphere', 
                                radius: 5,
                                color:'black'}, 
                          transform:{}, 
                          children:[]}, 
                        { id:'sphere2',
                          form:{type:'sphere',
                                radius: 10,
                                opacity:0.4,
                                wireframe:true}, 
                          transform:{}, 
                          children:[]} 
                      ]//actors
                    };//Model1

